version: '3.8'

services:
  proyecto-bancario-microservicio:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./proyecto_bancario.db:/usr/src/app/proyecto_bancario.db
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

